name: Upload dotnet package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          cache: true
      - name: Build project and pack NuGet package
        run: dotnet pack HealthCheckDashboard.NET/HealthCheckDashboard.NET.csproj -c Release -o out-HealthCheckDashboard

      - name: Push generated package to GitHub Packages registry
        run: dotnet nuget push out-HealthCheckDashboard/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -n --api-key ${{secrets.NUGET}}
